# Generated by Django 5.2.1 on 2025-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'أدمن'), ('user', 'مستخدم عادي')], default='user', max_length=20),
        ),
    ]
